apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jekyll-site-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jekyll-site-dev
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: kustomized_helm/overlays/dev
    repoURL: https://github.com/jtmack6/argocd-jekyll-site
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
